# Generated by Django 6.0 on 2025-12-18 15:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Name of the criterion (e.g., 'Completeness')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the criterion')),
                ('category', models.CharField(blank=True, help_text='Category/group of the criterion', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Order within the framework')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['framework', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_text', models.TextField(help_text='The definition text')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='frameworks.criterion')),
            ],
            options={
                'ordering': ['criterion', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the framework (e.g., 'Chen et al. 2019')", max_length=200)),
                ('authors', models.CharField(blank=True, help_text='Authors of the framework', max_length=500)),
                ('year', models.IntegerField(blank=True, help_text='Publication year', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('title', models.CharField(blank=True, help_text='Title of the paper', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Description of the framework')),
                ('source', models.CharField(blank=True, help_text='Source/venue of publication', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'name'],
                'indexes': [models.Index(fields=['name'], name='frameworks__name_d5bf92_idx'), models.Index(fields=['year'], name='frameworks__year_deb742_idx')],
            },
        ),
        migrations.AddField(
            model_name='criterion',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='frameworks.framework'),
        ),
        migrations.AddIndex(
            model_name='criterion',
            index=models.Index(fields=['name'], name='frameworks__name_1e4f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='criterion',
            index=models.Index(fields=['framework', 'name'], name='frameworks__framewo_0a06ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='criterion',
            unique_together={('framework', 'name')},
        ),
    ]
