# Generated by Django 6.0 on 2025-12-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='accuracy',
            field=models.CharField(blank=True, help_text='Accuracy or performance metrics', max_length=200),
        ),
        migrations.AddField(
            model_name='framework',
            name='advantages',
            field=models.TextField(blank=True, help_text='Advantages of the framework'),
        ),
        migrations.AddField(
            model_name='framework',
            name='algorithm_used',
            field=models.CharField(blank=True, help_text='Algorithm or technique used', max_length=500),
        ),
        migrations.AddField(
            model_name='framework',
            name='drawbacks',
            field=models.TextField(blank=True, help_text='Drawbacks or limitations'),
        ),
        migrations.AddField(
            model_name='framework',
            name='methodology',
            field=models.TextField(blank=True, help_text='Methodology used in the framework'),
        ),
        migrations.AddField(
            model_name='framework',
            name='objectives',
            field=models.TextField(blank=True, help_text='Objectives of the framework'),
        ),
        migrations.AddField(
            model_name='framework',
            name='top_model',
            field=models.CharField(blank=True, help_text='Top model or main contribution', max_length=200),
        ),
        migrations.AlterField(
            model_name='framework',
            name='description',
            field=models.TextField(blank=True, help_text='Abstract/Description of the framework'),
        ),
    ]
