# Generated by Django 6.0 on 2025-12-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0002_framework_accuracy_framework_advantages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='author',
            field=models.CharField(blank=True, help_text='Author(s) who defined this criterion (defaults to framework authors)', max_length=500),
        ),
    ]
